Reusable actions
opensafely/post-covid-neurodegenerative pull request #24
Opened 2022-11-30 15:24 UTC by josephignace

2023-01-13 14:50 UTC, marwaalarab requested changes
In create_project actions all intermediate files which don't need to be reviewed must be compressed like index_dates... also you might need to convert the feather file in preliminary study definition (better to check with Venexia)

2023-02-02 10:02 UTC, A-Whitmarsh approved these changes

2023-02-02 10:07 UTC, josephignace commented
> 

Changes have been addressed. I confirmed with Venexia the create_project_actions. To make sure, I used the grastrointestinal repo as reference to compress the files.

2023-02-02 18:07 UTC, marwaalarab reviewed
Hi Jose, 
The changes look fine. There is a file describe-file.R and its action code in create_actions.R that  I copied from MH you might want to add it too?

2023-02-03 15:13 UTC, marwaalarab approved these changes

2023-02-03 15:14 UTC, merged