Stata models
opensafely/post-covid-neurodegenerative pull request #84
Opened 2024-04-17 09:12 UTC by josephignace

Prepared scripts for Stata models.
Models to be run using Stata needs to be updated

2024-04-24 13:32 UTC, venexia requested changes
Hi Jose. Thank you for providing the action name so I could test this locally. I have confirmed the code works. However, the Stata code is expecting three inputs (cpf, day0, extf) and you have only specified one in your action - please can you resolve this? Also, there is an optional change, which is to make a single model output file for both R and Stata results.

2024-04-25 15:40 UTC, venexia requested changes
Hi Jose. Thank you for addressing the comments. One further change is required. The input for the argument `day0` is `TRUE`/`FALSE` depending on whether you want an estimate for day zero (`TRUE`) or not (`FALSE`). Currently, you have set the parameter to be the name - for instance, for the action 'stata_cox_ipw-cohort_prevax-main-vascular_dementia', the argument `day0` is set to `cohort_prevax-main-vascular_dementia`.

2024-05-02 15:02 UTC, josephignace commented
Day0 argument added (following MH approach).
Files names changed in the cox_model.do ("ready-").
Simplified list of models to be run using Stata and Stata output added (create project actions) to test the analysis locally (this will be changed to the full list once the PR is ready).

2024-05-10 12:51 UTC, venexia approved these changes
Looks good. Thanks, Jose.

2024-05-10 13:02 UTC, josephignace commented on analysis/stata/cox_model.do
> +export delimited using "output/ready-`name'_median_fup.csv", replace
I made the change, both cox_model.do and create_project_actions.

2024-05-10 13:03 UTC, josephignace commented
@venexia Should I merge this PR? Or should I wait for the output release to update the list of models to be run using Stata (I would prefer this option)?

2024-05-16 11:18 UTC, merged